#!/bin/bash

path=

help () {
echo "
Siteman by Jack Berendt.

Type a command such as:
	h or help: displays this message
	p or path: takes the argument after the command and sets it as your website's path.
	n or new: Creates a new file from a template and opens it in ${EDITOR}. Example: 'siteman n post test.html'
	s or setup: Sets up siteman in the specified path.
"
}




if [ $1 ]; 
then
if [ $1 == "path" ] || [ $1 == "p" ]; 
then
	sed -i "s|^path.*|path=${2}|" $0
elif [ $1 == "help" ] || [ $1 == "h" ]; 
then
	help
elif [ $1 == "setup" ] || [ $1 == "s" ]; 
then
	mkdir $path/templates
elif [ $1 == "new" ] || [ $1 == "n" ];
then
	cp $path/templates/$2 $path/$3
	$EDITOR $path/$3

fi
else 
	help
fi
